services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:dev
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules
    restart: always
    depends_on:
    - database

  database:
    container_name: database
    build:
      context: .
      dockerfile: ./src/database/Dockerfile
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

networks:
  database:
    name: database
    driver: bridge   
volumes:
  postgres_data: 